// Package schema dumps a ClickHouse database's schema into a normalized,
// deterministic form, diffs a live server against it (drift), and lints
// golang-migrate-style migration files. The normalizer maps ClickHouse Cloud's
// Shared* engines back to their OSS equivalents so a Cloud dump and an OSS dump
// compare equal.
package schema

import (
	"bufio"
	"cmp"
	"context"
	"fmt"
	"maps"
	"regexp"
	"slices"
	"strings"

	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

type Conn = driver.Conn

type Object struct {
	Name string
	IsMV bool
	DDL  string // normalized, no trailing semicolon
}

// Dump reads every table/MV in db (skipping names in exclude and .inner* MV
// storage) and returns them normalized and sorted (tables first, then MVs).
func Dump(ctx context.Context, conn Conn, db string, exclude ...string) ([]Object, error) {
	skip := map[string]bool{}
	for _, e := range exclude {
		skip[e] = true
	}
	rows, err := conn.Query(ctx,
		"SELECT name, engine, create_table_query FROM system.tables WHERE database = ? AND name NOT LIKE '.inner%' ORDER BY name", db)
	if err != nil {
		return nil, fmt.Errorf("query system.tables: %w", err)
	}
	defer rows.Close()
	var objs []Object
	for rows.Next() {
		var name, engine, ddl string
		if err := rows.Scan(&name, &engine, &ddl); err != nil {
			return nil, err
		}
		if skip[name] {
			continue
		}
		objs = append(objs, Object{Name: name, IsMV: engine == "MaterializedView", DDL: Normalize(ddl)})
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	sortObjects(objs)
	return objs, nil
}

func sortObjects(objs []Object) {
	slices.SortFunc(objs, func(a, b Object) int {
		if a.IsMV != b.IsMV {
			if a.IsMV {
				return 1
			}
			return -1
		}
		return cmp.Compare(a.Name, b.Name)
	})
}

// Render produces a schema-file text for a set of objects.
func Render(objs []Object) string {
	var b strings.Builder
	b.WriteString("-- Generated by chtool/schema; DO NOT EDIT.\n\n")
	for _, o := range objs {
		kind := "table"
		if o.IsMV {
			kind = "materialized view"
		}
		fmt.Fprintf(&b, "-- name: %s (%s)\n%s;\n\n", o.Name, kind, o.DDL)
	}
	return b.String()
}

// Parse reads Render output back into objects.
func Parse(text string) ([]Object, error) {
	var objs []Object
	var cur *Object
	var body strings.Builder
	flush := func() {
		if cur != nil {
			cur.DDL = strings.TrimSpace(strings.TrimRight(strings.TrimSpace(body.String()), ";"))
			objs = append(objs, *cur)
		}
		cur = nil
		body.Reset()
	}
	sc := bufio.NewScanner(strings.NewReader(text))
	sc.Buffer(make([]byte, 0, 64*1024), 8*1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if name, kind, ok := parseNameMarker(line); ok {
			flush()
			cur = &Object{Name: name, IsMV: kind == "materialized view"}
			continue
		}
		if cur == nil {
			continue
		}
		body.WriteString(line)
		body.WriteString("\n")
	}
	flush()
	return objs, sc.Err()
}

func parseNameMarker(line string) (name, kind string, ok bool) {
	const p = "-- name: "
	if !strings.HasPrefix(line, p) {
		return "", "", false
	}
	rest := strings.TrimPrefix(line, p)
	if i := strings.LastIndex(rest, " ("); i >= 0 && strings.HasSuffix(rest, ")") {
		return strings.TrimSpace(rest[:i]), rest[i+2 : len(rest)-1], true
	}
	return strings.TrimSpace(rest), "table", true
}

// Diff compares expected (want) with a live dump (got); an empty slice means no
// drift. Objects whose name is in ignore are skipped.
func Diff(want, got []Object, ignore map[string]bool) []string {
	byName := func(o []Object) map[string]Object {
		m := make(map[string]Object, len(o))
		for _, x := range o {
			m[x.Name] = x
		}
		return m
	}
	w, g := byName(want), byName(got)
	names := map[string]struct{}{}
	for n := range w {
		names[n] = struct{}{}
	}
	for n := range g {
		names[n] = struct{}{}
	}
	var report []string
	for _, n := range slices.Sorted(maps.Keys(names)) {
		if ignore[n] {
			continue
		}
		wo, inW := w[n]
		go_, inG := g[n]
		switch {
		case inW && !inG:
			report = append(report, fmt.Sprintf("- %s: in schema but MISSING on server", n))
		case !inW && inG:
			report = append(report, fmt.Sprintf("- %s: on server but NOT in schema (untracked)", n))
		case wo.DDL != go_.DDL:
			report = append(report, fmt.Sprintf("- %s: DDL differs", n))
		}
	}
	return report
}

var (
	sharedEngineRe       = regexp.MustCompile(`(?i)\b(?:Shared|Replicated)(\w*?MergeTree)\s*\(([^)]*)\)`)
	defaultGranularityRe = regexp.MustCompile(`(?i)index_granularity\s*=\s*8192\b`)
	doubleCommaRe        = regexp.MustCompile(`,\s*,`)
	settingsCommaRe      = regexp.MustCompile(`(?i)(SETTINGS)\s*,`)
	trailingCommaRe      = regexp.MustCompile(`,\s*\z`)
	emptySettingsRe      = regexp.MustCompile(`(?i)\s*SETTINGS\s*(?:;|\z)`)
	whitespaceRe         = regexp.MustCompile(`\s+`)
	clauseRe             = regexp.MustCompile(`(?i)\s+(ENGINE|PARTITION BY|PRIMARY KEY|ORDER BY|SAMPLE BY|TTL|SETTINGS)\s+`)
	asSelectRe           = regexp.MustCompile(`(?i)\s+AS\s+(SELECT|WITH|\()`)
)

// Normalize converts a raw create_table_query into a canonical, deterministic
// form: Cloud Shared*/Replicated* engines are mapped to their OSS equivalents,
// the default index_granularity is stripped, and the DDL head is reflowed by
// clause. An MV's SELECT body is preserved verbatim (only whitespace-collapsed).
func Normalize(ddl string) string {
	ddl = strings.TrimSpace(ddl)
	ddl = normalizeEngine(ddl)
	ddl = defaultGranularityRe.ReplaceAllString(ddl, "")
	// Removing a mid-list index_granularity leaves a stray comma; heal it.
	ddl = doubleCommaRe.ReplaceAllString(ddl, ",")
	ddl = settingsCommaRe.ReplaceAllString(ddl, "$1 ")
	ddl = trailingCommaRe.ReplaceAllString(ddl, "")
	ddl = emptySettingsRe.ReplaceAllString(ddl, "")

	head, tail := ddl, ""
	if loc := asSelectRe.FindStringIndex(ddl); loc != nil {
		head = ddl[:loc[0]]
		tail = strings.TrimSpace(ddl[loc[0]:])
	}
	head = strings.TrimSpace(whitespaceRe.ReplaceAllString(head, " "))
	head = clauseRe.ReplaceAllString(head, "\n$1 ")
	if tail != "" {
		return head + "\n" + whitespaceRe.ReplaceAllString(tail, " ")
	}
	return head
}

// normalizeEngine maps a Cloud Shared*/Replicated* MergeTree engine to its OSS
// equivalent, dropping the leading (zk_path, replica) arguments while keeping
// any trailing semantic args (e.g. ReplacingMergeTree's version column).
func normalizeEngine(ddl string) string {
	return sharedEngineRe.ReplaceAllStringFunc(ddl, func(match string) string {
		sub := sharedEngineRe.FindStringSubmatch(match)
		base, args := sub[1], sub[2]
		rest := splitEngineArgs(args)
		if len(rest) > 2 {
			return base + "(" + strings.Join(rest[2:], ", ") + ")"
		}
		return base
	})
}

// splitEngineArgs splits on top-level commas, ignoring those inside quotes.
func splitEngineArgs(s string) []string {
	if strings.TrimSpace(s) == "" {
		return nil
	}
	var out []string
	var b strings.Builder
	inQuote := false
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '\'':
			inQuote = !inQuote
			b.WriteByte(c)
		case c == ',' && !inQuote:
			out = append(out, strings.TrimSpace(b.String()))
			b.Reset()
		default:
			b.WriteByte(c)
		}
	}
	return append(out, strings.TrimSpace(b.String()))
}
